os:
  - linux
  - osx
  
language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
      
      
cache:
  directories:
    - node_modules

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
after_script:
  - npm start

notifications:
  slack: leduong:8FHnajypcfOykiQS6Hn6QBB5
repo_token: RowsKbZ85YsRTAjF5d50i4rkAd3FArlu8
